name: Codex review integration

on:
  push:
    branches: [ "master" ]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  codex-review:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.CODEX_API_KEY }}
      CODEX_QUIET_MODE: 1 #deshabilita el modo consola para git action
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Ensure bootstrap/cache directory exists
        run: mkdir -p bootstrap/cache

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --prefer-dist


      - name: Install Codex CLI
        run: npm install -g @openai/codex


      # Ejemplo de paso: actualizar changelog automáticamente
      - name: Auto-update CHANGELOG with Codex
        run: |
          export CODEX_QUIET_MODE=1
          codex --no-terminal  -a auto-edit "Update CHANGELOG for next release"


      # Otro paso: revisión de seguridad (puedes duplicar con diferentes prompts)
      - name: Security review with Codex
        run: |
          codex --quiet "Look for vulnerabilities and create a security review report"

      # Otro paso: sugerencia de PRs útiles
      - name: Suggest high-impact PRs
        run: |
          codex --quiet "Carefully review this repo, and propose 3 high impact well-scoped PRs"
